name: 'Infometrics-articles'
branding:
  icon: 'user'
  color: 'blue'
description: 'Формирование топ-списка статей Инфостарт для моего профиля GitHub'
inputs:
  user_id:
    description: 'Infostart ID'
    required: true
  count:
    description: 'Количество статей с максимальным количеством плюсов'
    required: true
    default: '5'
  template_file:
    description: 'Путь к файлу шаблона'
    required: false
    default: 'template.html'
  readme_file:
    description: 'Путь к файлу README'
    required: false
    default: 'README.md'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Установка зависимостей
      uses: py-actions/py-dependency-install@v4
      with:
        path: ${{ github.action_path }}/requirements.txt
    - name: Запуск скрипта
      run: python ${{ github.action_path }}/main.py ${{ inputs.user_id }} ${{ inputs.count }} ${{ github.action_path }}/template.html ${{ inputs.readme_file }}
      shell: bash
    - name: Запись изменений
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: SerVer1C (bot)
        commit_user_email: serverxplanet@gmail.com
        commit_author: SerVer1C <serverxplanet@gmail.com>
        commit_message: Обновление списка топ статей Инфостарт в README.md